# Generated by Django 2.0 on 2020-05-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200501_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoapp.City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profpic',
            field=models.ImageField(default=1, upload_to='profpics'),
            preserve_default=False,
        ),
    ]
