# Generated by Django 2.0 on 2020-05-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20200502_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userprof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.UserProfile')),
            ],
        ),
    ]
