# Generated by Django 2.0 on 2020-05-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todotype', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoapp.Status'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='todotype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoapp.ToDoType'),
        ),
    ]
