# Generated by Django 2.0 on 2020-06-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_todolist_textnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todopoint', models.CharField(max_length=300)),
                ('todolistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.ToDoList')),
            ],
        ),
    ]
